apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: <STORAGE_CLASS>
provisioner: kubernetes.io/glusterfs
parameters:
  resturl: "http://<HEKETI_URL>"
  restuser: "admin"
  secretNamespace: "<NAMESPACE>"
  secretName: "heketi-<NAMESPACE>-admin-secret"
